# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager


moveit_simple_controller_manager:
  controller_names:
    - kerby_arm_moveit_controller

  kerby_arm_moveit_controller:
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
      - finger1
  
  kerby_left_moveit_controller:
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - pivot_gauche
      - steering1
      - driving1
      - steering4
      - driving4
      - pivot_droit
      - steering2
      - driving2
      - steering3
      - driving3