# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    kerby_arm_moveit_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    kerby_left_moveit_controller:
      type: position_controllers/JointGroupPositionController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster


kerby_arm_moveit_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
      - finger1
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

kerby_left_moveit_controller:
  ros__parameters:
    joints:
      - pivot_gauche
      - steering1
      - driving1
      - steering4
      - driving4
      - pivot_droit
      - steering2
      - driving2
      - steering3
      - driving3
    command_interfaces:
      - position
    state_interfaces:
      - position