<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="bonk">
<!-- ======================================================================================================================== -->




	<!-- ==========CONSANTS========== -->



	<!-- base_link constants -->
	<xacro:property name="base_link_dim_x" value="0.3" />
	<xacro:property name="base_link_dim_y" value="0.3" />
	<xacro:property name="base_link_dim_z" value="0.1" />
	<xacro:property name="base_link_dim" value="0.3 0.3 0.1" />
	<xacro:property name="base_link_btm_shift_x" value="0" />
	<xacro:property name="base_link_btm_shift_y" value="0" />
	<xacro:property name="base_link_btm_shift_z" value="0" />
	<xacro:property name="base_link_top_shift_x" value="0" />
	<xacro:property name="base_link_top_shift_y" value="0" />
	<xacro:property name="base_link_top_shift_z" value="${(base_link_dim_z/2)}" />
	<xacro:property name="base_link_origin" value="0 0 0" />
	<xacro:property name="base_link_attach_point" value="0 0 ${((base_link_dim_z/2)+0)}" />



	<!-- link1 constants -->
	<xacro:property name="link1_dim_x" value="0.083" />
	<xacro:property name="link1_dim_y" value="0.156" />
	<xacro:property name="link1_dim_z" value="0.14" />
	<xacro:property name="link1_dim" value="0.083 0.156 0.14" />
	<xacro:property name="link1_btm_shift_x" value="0" />
	<xacro:property name="link1_btm_shift_y" value="0" />
	<xacro:property name="link1_btm_shift_z" value="${(link1_dim_z/2)}" />
	<xacro:property name="link1_top_shift_x" value="0" />
	<xacro:property name="link1_top_shift_y" value="0" />
	<xacro:property name="link1_top_shift_z" value="${((link1_dim_z/2)-0.05)}" />
	<xacro:property name="link1_origin" value="0 0 ${(link1_dim_z/2)}" />
	<xacro:property name="link1_attach_point" value="0 0 ${(((link1_dim_z/2)-0.05)+(link1_dim_z/2))}" />



	<!-- link2 constants -->
	<xacro:property name="link2_dim_x" value="0.096" />
	<xacro:property name="link2_dim_y" value="0.062" />
	<xacro:property name="link2_dim_z" value="0.425" />
	<xacro:property name="link2_dim" value="0.096 0.062 0.425" />
	<xacro:property name="link2_btm_shift_x" value="0" />
	<xacro:property name="link2_btm_shift_y" value="0" />
	<xacro:property name="link2_btm_shift_z" value="${-((0.048-(link2_dim_z/2)))}" />
	<xacro:property name="link2_top_shift_x" value="${(0.03224-(link2_dim_x/2))}" />
	<xacro:property name="link2_top_shift_y" value="0" />
	<xacro:property name="link2_top_shift_z" value="${((link2_dim_z/2)-0.032224)}" />
	<xacro:property name="link2_origin" value="0 0 ${-((0.048-(link2_dim_z/2)))}" />
	<xacro:property name="link2_attach_point" value="${((0.03224-(link2_dim_x/2))+0)} 0 ${(((link2_dim_z/2)-0.032224)+-((0.048-(link2_dim_z/2))))}" />



	<!-- link3 constants -->
	<xacro:property name="link3_dim_x" value="0.092" />
	<xacro:property name="link3_dim_y" value="0.112" />
	<xacro:property name="link3_dim_z" value="0.334" />
	<xacro:property name="link3_dim" value="0.092 0.112 0.334" />
	<xacro:property name="link3_btm_shift_x" value="${(0.01615-(link3_dim_x/2))}" />
	<xacro:property name="link3_btm_shift_y" value="0" />
	<xacro:property name="link3_btm_shift_z" value="${-((0.096328-(link3_dim_z/2)))}" />
	<xacro:property name="link3_top_shift_x" value="${-((0.0415-(link3_dim_x/2)))}" />
	<xacro:property name="link3_top_shift_y" value="0" />
	<xacro:property name="link3_top_shift_z" value="${(link3_dim_z/2)}" />
	<xacro:property name="link3_origin" value="${(0.01615-(link3_dim_x/2))} 0 ${-((0.096328-(link3_dim_z/2)))}" />
	<xacro:property name="link3_attach_point" value="${(-((0.0415-(link3_dim_x/2)))+(0.01615-(link3_dim_x/2)))} 0 ${((link3_dim_z/2)+-((0.096328-(link3_dim_z/2))))}" />



	<!-- link4 constants -->
	<xacro:property name="link4_dim_x" value="0.08" />
	<xacro:property name="link4_dim_y" value="0.173" />
	<xacro:property name="link4_dim_z" value="0.12" />
	<xacro:property name="link4_dim" value="0.08 0.173 0.12" />
	<xacro:property name="link4_btm_shift_x" value="0" />
	<xacro:property name="link4_btm_shift_y" value="0" />
	<xacro:property name="link4_btm_shift_z" value="${(link4_dim_z/2)}" />
	<xacro:property name="link4_top_shift_x" value="0" />
	<xacro:property name="link4_top_shift_y" value="0" />
	<xacro:property name="link4_top_shift_z" value="${((link4_dim_z/2)-0.029)}" />
	<xacro:property name="link4_origin" value="0 0 ${(link4_dim_z/2)}" />
	<xacro:property name="link4_attach_point" value="0 0 ${(((link4_dim_z/2)-0.029)+(link4_dim_z/2))}" />



	<!-- link5 constants -->
	<xacro:property name="link5_dim_x" value="0.047" />
	<xacro:property name="link5_dim_y" value="0.056" />
	<xacro:property name="link5_dim_z" value="0.08625" />
	<xacro:property name="link5_dim" value="0.047 0.056 0.08625" />
	<xacro:property name="link5_btm_shift_x" value="0" />
	<xacro:property name="link5_btm_shift_y" value="0" />
	<xacro:property name="link5_btm_shift_z" value="${((link5_dim_z/2)-0.0235)}" />
	<xacro:property name="link5_top_shift_x" value="0" />
	<xacro:property name="link5_top_shift_y" value="0" />
	<xacro:property name="link5_top_shift_z" value="${(link5_dim_z/2)}" />
	<xacro:property name="link5_origin" value="0 0 ${((link5_dim_z/2)-0.0235)}" />
	<xacro:property name="link5_attach_point" value="0 0 ${((link5_dim_z/2)+((link5_dim_z/2)-0.0235))}" />



	<!-- gripper_base constants -->
	<xacro:property name="gripper_base_dim_x" value="0.1196" />
	<xacro:property name="gripper_base_dim_y" value="0.1105" />
	<xacro:property name="gripper_base_dim_z" value="0.062" />
	<xacro:property name="gripper_base_dim" value="0.1196 0.1105 0.062" />
	<xacro:property name="gripper_base_btm_shift_x" value="${((gripper_base_dim_x/2)-0.03)}" />
	<xacro:property name="gripper_base_btm_shift_y" value="0" />
	<xacro:property name="gripper_base_btm_shift_z" value="${(gripper_base_dim_z/2)}" />
	<xacro:property name="gripper_base_top_shift_x" value="0" />
	<xacro:property name="gripper_base_top_shift_y" value="0" />
	<xacro:property name="gripper_base_top_shift_z" value="0" />
	<xacro:property name="gripper_base_origin" value="${((gripper_base_dim_x/2)-0.03)} 0 ${(gripper_base_dim_z/2)}" />
	<xacro:property name="gripper_base_attach_point" value="${(((gripper_base_dim_x/2)-0.03)+0)} 0 ${((gripper_base_dim_z/2)+0)}" />

	<!-- ======================================================================================================================== -->




	<!-- ==========LINKS========== -->


	<!-- base_link -->
	<link name="base_link">
		<visual>
			<geometry>
				<box size="${base_link_dim}"/>
			</geometry>
			<origin xyz="${base_link_origin}" />
		</visual>
		<collision>
			<geometry>
				<box size="${base_link_dim}"/>
			</geometry>
			<origin xyz="${base_link_origin}" />
		</collision>
	</link>

	<!-- link1 -->
	<link name="link1">
		<visual>
			<geometry>
				<box size="${link1_dim}"/>
			</geometry>
			<origin xyz="${link1_origin}" />
		</visual>
		<collision>
			<geometry>
				<box size="${link1_dim}"/>
			</geometry>
			<origin xyz="${link1_origin}" />
		</collision>
	</link>

	<!-- link2 -->
	<link name="link2">
		<visual>
			<geometry>
				<box size="${link2_dim}"/>
			</geometry>
			<origin xyz="${link2_origin}" />
		</visual>
		<collision>
			<geometry>
				<box size="${link2_dim}"/>
			</geometry>
			<origin xyz="${link2_origin}" />
		</collision>
	</link>

	<!-- link3 -->
	<link name="link3">
		<visual>
			<geometry>
				<box size="${link3_dim}"/>
			</geometry>
			<origin xyz="${link3_origin}" />
		</visual>
		<collision>
			<geometry>
				<box size="${link3_dim}"/>
			</geometry>
			<origin xyz="${link3_origin}" />
		</collision>
	</link>

	<!-- link4 -->
	<link name="link4">
		<visual>
			<geometry>
				<box size="${link4_dim}"/>
			</geometry>
			<origin xyz="${link4_origin}" />
		</visual>
		<collision>
			<geometry>
				<box size="${link4_dim}"/>
			</geometry>
			<origin xyz="${link4_origin}" />
		</collision>
	</link>

	<!-- link5 -->
	<link name="link5">
		<visual>
			<geometry>
				<box size="${link5_dim}"/>
			</geometry>
			<origin xyz="${link5_origin}" />
		</visual>
		<collision>
			<geometry>
				<box size="${link5_dim}"/>
			</geometry>
			<origin xyz="${link5_origin}" />
		</collision>
	</link>

	<!-- gripper_base -->
	<link name="gripper_base">
		<visual>
			<geometry>
				<box size="${gripper_base_dim}"/>
			</geometry>
			<origin xyz="${gripper_base_origin}" />
		</visual>
		<collision>
			<geometry>
				<box size="${gripper_base_dim}"/>
			</geometry>
			<origin xyz="${gripper_base_origin}" />
		</collision>
	</link>
	<!-- ======================================================================================================================== -->




	<!-- ==========JOINTS========== -->


	<!-- joint1 -->
	<joint name="joint1" type="revolute">
		<parent link="base_link"/>
		<child link="link1"/>
		<origin xyz="${base_link_attach_point}" />
		<axis xyz="0 0 1"/>
		<limit effort="1000" velocity="0.5" lower="${-(pi)}" upper="${pi}"/>
	</joint>

	<!-- joint2 -->
	<joint name="joint2" type="revolute">
		<parent link="link1"/>
		<child link="link2"/>
		<origin xyz="${link1_attach_point}" />
		<axis xyz="0 1 0"/>
		<limit effort="1000" velocity="0.5" lower="${-(pi)}" upper="${pi}"/>
	</joint>

	<!-- joint3 -->
	<joint name="joint3" type="revolute">
		<parent link="link2"/>
		<child link="link3"/>
		<origin xyz="${link2_attach_point}" />
		<axis xyz="0 1 0"/>
		<limit effort="1000" velocity="0.5" lower="${-(pi)}" upper="${pi}"/>
	</joint>

	<!-- joint4 -->
	<joint name="joint4" type="revolute">
		<parent link="link3"/>
		<child link="link4"/>
		<origin xyz="${link3_attach_point}" />
		<axis xyz="0 0 1"/>
		<limit effort="1000" velocity="0.5" lower="${-(pi)}" upper="${pi}"/>
	</joint>

	<!-- joint5 -->
	<joint name="joint5" type="revolute">
		<parent link="link4"/>
		<child link="link5"/>
		<origin xyz="${link4_attach_point}" />
		<axis xyz="0 1 0"/>
		<limit effort="1000" velocity="0.5" lower="${-(pi)}" upper="${pi}"/>
	</joint>

	<!-- joint6 -->
	<joint name="joint6" type="revolute">
		<parent link="link5"/>
		<child link="gripper_base"/>
		<origin xyz="${link5_attach_point}" />
		<axis xyz="0 0 1"/>
		<limit effort="1000" velocity="0.5" lower="${-(pi)}" upper="${pi}"/>
	</joint>




</robot>