# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    kerby_arm_moveit_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    kerby_base_moveit_controller:
      type: position_controllers/JointGroupPositionController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster


kerby_arm_moveit_controller:
  ros__parameters:
    joints:
      - hd_joint1
      - hd_joint2
      - hd_joint3
      - hd_joint4
      - hd_joint5
      - hd_joint6
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
