controller_manager:
  ros__parameters:
    update_rate: 1000 # Hz

    position_controller:
      type: position_controllers/JointGroupPositionController

    velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    hd_pos_controller:
      #type: joint_trajectory_controller/JointTrajectoryController #from hd repo
      type: position_controllers/JointGroupPositionController

    hd_vel_controller:
      type: velocity_controllers/JointGroupVelocityController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster




position_controller:
  ros__parameters:
     joints:
      - steering1
      - steering2
      - steering3
      - steering4
     interface_name: position
     command_interfaces:
       - position
     state_interfaces:
       - position
       - velocity

velocity_controller:
  ros__parameters:
    joints:
      - driving1
      - driving2
      - driving3
      - driving4
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity


hd_pos_controller:
  ros__parameters:
    joints:
      - hd_joint1
      - hd_joint2
      # - hd_joint3
      # - hd_joint4
      # - hd_joint5
      # - hd_joint6



      
    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - velocity

joint_state_broadcaster:
  ros__parameters:
    publish_rate: 100.0
    use_sim_time: true